vich_uploader:
    db_driver: orm

    mappings:
        product_image:
            uri_prefix: /images/products
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            upload_destination: '%kernel.project_dir%/public/images/products'
