vich_uploader:
    db_driver: orm

    mappings:
        product_image:
            uri_prefix: /l-echalote/public/images/products
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            upload_destination: '%kernel.root_dir%/../public/images/products'
